basic:
    name: 'Homescreen-Mira Tablet UI Comparison'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'https://Lenovo%20A9.7%22)%20Landscape:'
        - 'https://-%20Width:%201280px'
        - 'https://-%20Height:%20800px'
        - 'https://-%20Mode%20:%20Landscape%22'
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
